// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh YOUR_PACKAGE_NAME
// **************************************************************************

// ignore_for_file: unused_import, directives_ordering
import 'package:trans_trackid_example/app/app.dart';
import 'package:trans_trackid_example/utils/typedef.dart';
import 'package:trans_trackid_example/utils/get_it.dart';
import 'package:trans_trackid_example/utils/constant.dart';
import 'package:trans_trackid_example/utils/enum.dart';
import 'package:trans_trackid_example/repositories/main_repository.dart';
import 'package:trans_trackid_example/repositories/devices_repository.dart';
import 'package:trans_trackid_example/models/meta.dart';
import 'package:trans_trackid_example/models/device.dart';
import 'package:trans_trackid_example/models/base_response.dart';
import 'package:trans_trackid_example/modules/splash/cubit/splash_cubit.dart';
import 'package:trans_trackid_example/modules/splash/view/splash_page.dart';
import 'package:trans_trackid_example/modules/location_devices/cubit/location_devices_cubit.dart';
import 'package:trans_trackid_example/modules/location_devices/view/location_devices_page.dart';
import 'package:trans_trackid_example/services/api_services.dart';

void main(){}