name: flutter_tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.5'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ad276a6a-5ff1-4eaf-b88c-7be5d7cdf9c0 